name: npm PR Test

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - dev
  push:
    branches:
      - feature/**

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./codebase/rdicidr-0.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '15.0.1'

      - name: Install dependencies
        run: npm install